### ISSUE TITLE
Comments on Usability: Version 2.4.4 vs. Version 1.1.1

### ISSUE THREAD

**Issue by megbaker20** [iDigBio/idigbio-media-appliance#1]
Below are three situations where I think version 1.1.1 executed actions more effectively or version 2.4.4 could improve:

1.	File Download Location – decreased efficiency since 1.1.1

In version 1.1.1 of the Ingestion Utility Tool, the user determined the download location of the media_records.csv and the download location and name of the export report. In this version 2.4.4, the file populates in the Downloads folder on the computer and is named with letters and numbers, such as ‘23099d05-0bb7-4332-b069-59efdeafd6ed.csv’. This format requires added manipulation of the location and name of the file. 

2.	Upload History 

Version 1.1.1 of the Ingestion Utility Tool tracked export reports by session, allowing for the user to return to any given upload and re-download the export report if needed. In version 2.4.4, the upload history is more generalized and provides only the history from the ‘Last day’, ‘Last 7 days’, ‘Last 30 days’ or ‘Show All’, but doesn’t allow the user to download the export report for older ingestion sessions (older than the active/immediate session). This makes it more difficult to locate individual images and impossible to re-export a single session if a user needed to revisit the upload history more than one day after the uploading session. 

Although we save the export reports every time we upload, there has been an instance where I accidentally deleted an export report. I needed to re-download the report for that session. Using version 1.1.1, it was as easy as finding the individual export report in the upload history and re-downloading it. In this version, it can become tricky if multiple uploads have happened and more than one day has gone by since my upload of interest. 

3.	Rights License

If a user selects the ‘Generate CSV & Upload Files’ option within the Generate CSV tab, it is uncertain which Image License is being attached to the images. Unlike version 1.1.1, this version does not have a column in the export report stating which license is being used when uploading the images.

**Comment by godfoder** [comment]
Thank you for your feedback. Usability was a big reason for the changes between version 1 and 2, so we appreciate your comments.

1. In moving from 1 to 2, since the user interface for the appliance is the browser, we wanted to make the appliance operate more like a standard web-page. In moving towards this goal, we replaced the text fields that required you to manually type or paste in paths on your file system with controls that work mostly like standard web file uploads and downloads. For downloads, in order to avoid accidentally overwriting files with the same name, we used random task identifers as the default file name supplied to the browser. What happens after that point is dependant on which browser you use and how you have it configured. For most browsers, the default is now to not prompt the user when a download is initiated, and to just save it to the default download location. You can change this behavior, but you have to do so for all downloads from that browser, not just the appliance.

I'll see what I can do about the filenames to make them more convenient. As a related aside, do you use the account alias feature in the appliance? Would replacing the filename with something like "<account alias>_<date>_media_export.csv" be sufficient?

2. Is there a specific use case or issue that is driving the need for having a report of only the most recent uploads? Currently the export functionality is somewhat designed to capture the complete state (including any updates to image files) and provide that as an export. Generally, that is the desired input for most tools that consume the data, as far as I am aware. I can certainly revisit the export functionality to provide more comprehensive options should it be required.

3. I'll work on adding that to the generate page for that case to make it more obvious which license the user has selected. I'll also try and get that added to the report generation.

**Comment by godfoder** [comment]
These issues should be mostly addressed in the latest release of the appliance (2.5.1). In most cases, your copy should automatically update itself to the latest release when you start it next.

**Comment by megbaker20** [comment]
Hey Alex,

Can you explain the account alias feature to me?

Also, I downloaded the new version and was trying to generate .csv but
received this error..
[image: Inline image 1]

Let me know if this means anything to you.

Thanks!
Meg
